id: org.ksmster.gedit
version: 1.0.0
type: Che Editor
name: gedit-sample
title: Gedit sample
description: Gedit sample
url: https://raw.githubusercontent.com/skabashnyuk/eclipse-che-plugins/master/org.ksmster.gedit/1.0.0/che-plugin.yaml
