apiVersion: v2
publisher: ksmster
name: che-editor-gedit
version: 1.0.0
type: Che Editor
displayName: Gedit IDE
title: GeditIDE for Eclipse Che
description: Gedit IDE
Icon: https://pbs.twimg.com/profile_images/929088242456190976/xjkS2L-0_400x400.jpg
category: Editor
repository: https://github.com/skabashnyuk/eclipse-che-plugins/
firstPublicationDate: "2019-02-05"
spec:
  endpoints:
    - name: "theia"
      public: true
      targetPort: 6080
      attributes:
          protocol: http
          type: ide
          discoverable: false
  containers:
    - name: theia-ide
      image: ksmster/che-editor-gedit:2019-05-17
      volumes:
        - mountPath: "/projects"
          name: projects
      ports:
          - exposedPort: 6080
      memoryLimit: "512M"