id: org.ksmster.broadway-sample
version: 1.0.0
type: Che Editor
name: broadway-sample
title: Alexander Larsson broadway docker sample
description: Alexander Larsson broadway docker sample
url: https://github.com/skabashnyuk/eclipse-che-plugins/raw/master/org.ksmster.broadway-sample/1.0.0/che-plugin.yaml
