id: org.eclipse.che.editor.jupyter
version: 1.0.0
type: Che Editor
name: jupyter-notebook
title: Jupyter Notebook as Editor for Eclipse Che
description: Jupyter Notebook as Editor for Eclipse Che
icon: https://jupyter.org/assets/main-logo.svg
url: https://github.com/skabashnyuk/eclipse-che-plugins/raw/master/org.eclipse.che.editor.jupyter/1.0.0/che-editor-plugin.tar.gz
